### ISSUE TITLE
Cannot find module './beautifier'

### ISSUE THREAD

**Issue by lassik** [Unibeautify/unibeautify-cli#16]
Installed on macOS High Sierra via:

```
sudo npm install --global unibeautify unibeautify-cli beautifier beautifier-prettydiff
sudo npm upgrade --global unibeautify unibeautify-cli beautifier beautifier-prettydiff
```

I get the following error when trying to run it from bash:

```
$ unibeautify
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './beautifier'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/unibeautify-cli/node_modules/unibeautify/dist/src/index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

There don't seem to be any node-specific environment variables set. `env | grep -iE '(npm|node)'` returns nothing.

I'll be happy to provide details, but I have no node/npm experience so I don't know what to send.

**Comment by szeck87** [comment]
The repo is fine, its just that the package hasn't been re-published in 2 years.  @Glavin001 I'll try publishing, if I don't have permissions I'll let you know.

**Comment by szeck87** [comment]
@lassik I pushed a new version, 0.2.0.  But I'm having trouble installing it from npm on my machine.  Working through this issue now.

**Comment by szeck87** [comment]
@lassik fixed with the latest, 0.2.1.

**Comment by lassik** [comment]
Thanks, I really appreciate the quick response :) `unibeautify --help` now works fine.

Unfortunately, I now get this:

```
$ unibeautify
(node:10207) UnhandledPromiseRejectionWarning: Error: Beautifier is missing a "name" property.
    at Unibeautify.validateBeautifier (/usr/local/lib/node_modules/unibeautify/dist/src/beautifier.js:265:19)
    at Unibeautify.loadBeautifier (/usr/local/lib/node_modules/unibeautify/dist/src/beautifier.js:259:14)
    at beautifiers.forEach.beautifier (/usr/local/lib/node_modules/unibeautify/dist/src/beautifier.js:274:48)
    at Array.forEach (<anonymous>)
    at Unibeautify.loadBeautifiers (/usr/local/lib/node_modules/unibeautify/dist/src/beautifier.js:274:21)
    at loadBeautifiers (/usr/local/lib/node_modules/unibeautify-cli/dist/index.js:29:34)
    at findInstalledBeautifiers.then (/usr/local/lib/node_modules/unibeautify-cli/dist/index.js:35:16)
(node:10207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My `node --version` is `v10.5.0`

**Comment by szeck87** [comment]
Don't use `beautifier-prettydiff`, use `@unibeautify/beautifier-prettydiff`

**Comment by Glavin001** [comment]
@szeck87 I had no idea https://www.npmjs.com/package/beautifier-prettier still existed while the updated package is https://www.npmjs.com/package/@unibeautify/beautifier-prettier 
We should deprecate `beautifier-prettier` with https://docs.npmjs.com/cli/deprecate 
Do you have sufficient access? 😃

**Comment by Glavin001** [comment]
Good 👁 , @lassik . It should definitely be changed to use `@unibeautify` scope, to sync with: https://github.com/Unibeautify/beautifier-prettydiff#installation
